name: Bug Report
description: Report a problem with GhostCleaner
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened?
      placeholder: A clear description of the problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
